Enable Array writes
mdeweerd/zha-toolkit pull request #210
Opened 2023-10-16 21:50 UTC by tomasbedrich

2023-10-16 23:51 UTC, mdeweerd requested changes
Do you have more information about how the generic method fails?

2023-10-16 23:51 UTC, mdeweerd commented on README.md
> +  attr_val: [65, 4, 0, 6, 0, 13, 1, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2]
The attr_type is 0x48 which is 72, which is type "Array", but 65 as the first byte of the attr_val which in the code is used as the code for the type is an LVBytes type.

It seems I have some devices which Arrays, but not writeable.  Unfortunately these devices do not respond to the read request on the array which could be a first step to checking how zigpy handles that type.

2023-10-17 11:15 UTC, tomasbedrich commented
> Do you have more information about how the generic method fails?

```
service: zha_toolkit.attr_write
data:
  ieee: button.ubisys_c4_5504_identify
  endpoint: 232
  cluster: 64512
  attribute: 1
  attr_type: 0x48
  attr_val: "41040006000d0106000206010d0206000206020d0306000206030d04060002"
  read_before_write: true
  read_after_write: false
  use_cache: false
```

```python
$ tail -f /config/home-assistant.log | grep "custom_components.zha_toolkit"
2023-10-17 13:11:26.669 INFO (MainThread) [custom_components.zha_toolkit] Running ZHA Toolkit service: <ServiceCall zha_toolkit.attr_write (c:01HCYNAQEB8VBEP9BNR4F4CTCA): ieee=button.ubisys_c4_5504_identify, endpoint=232, cluster=64512, attribute=1, attr_type=72, attr_val=41040006000d0106000206010d0206000206020d0306000206030d04060002, read_before_write=True, read_after_write=False, use_cache=False>
2023-10-17 13:11:26.670 DEBUG (MainThread) [custom_components.zha_toolkit] Got hass.data['zha']/gateway <custom_components.zha.core.gateway.ZHAGateway object at 0xffff9ada28d0>
2023-10-17 13:11:26.694 DEBUG (MainThread) [custom_components.zha_toolkit] module is <module 'custom_components.zha_toolkit' from '/config/custom_components/zha_toolkit/__init__.py'>
2023-10-17 13:11:26.700 DEBUG (MainThread) [custom_components.zha_toolkit.utils] Parameters '{'ieee': 'button.ubisys_c4_5504_identify', 'endpoint': 232, 'cluster': 64512, 'attribute': 1, 'attr_type': 72, 'attr_val': '41040006000d0106000206010d0206000206020d0306000206030d04060002', 'read_before_write': True, 'read_after_write': False, 'use_cache': False}'
2023-10-17 13:11:26.701 DEBUG (MainThread) [custom_components.zha_toolkit.utils] Final manf 'None'
2023-10-17 13:11:26.702 DEBUG (MainThread) [custom_components.zha_toolkit.utils] registry_entity RegistryEntry(entity_id='button.ubisys_c4_5504_identify', unique_id='00:1f:ee:00:00:00:9a:e3-1-3', platform='zha', aliases=set(), area_id=None, capabilities=None, config_entry_id='5e33ebc13289867554f7364db82af185', device_class=None, device_id='c2520a704c74c0b5a187208e684b55fc', disabled_by=None, entity_category=<EntityCategory.DIAGNOSTIC: 'diagnostic'>, hidden_by=None, icon=None, id='80e47e521f856efd43f9a429ec9a1715', has_entity_name=True, name=None, options={'conversation': {'should_expose': False}}, original_device_class='identify', original_icon=None, original_name='Identify', supported_features=0, translation_key=None, unit_of_measurement=None)
2023-10-17 13:11:26.702 DEBUG (MainThread) [custom_components.zha_toolkit.utils] registry_device DeviceEntry(area_id=None, config_entries={'5e33ebc13289867554f7364db82af185'}, configuration_url=None, connections={('zigbee', '00:1f:ee:00:00:00:9a:e3')}, disabled_by=None, entry_type=None, hw_version=None, id='c2520a704c74c0b5a187208e684b55fc', identifiers={('zha', '00:1f:ee:00:00:00:9a:e3')}, manufacturer='ubisys', model='C4 (5504)', name_by_user=None, name='ubisys C4 (5504)', suggested_area=None, sw_version='0x02120404', via_device_id='34cca87150cffeda1beaafec3e4619c1', is_new=False)
2023-10-17 13:11:26.705 DEBUG (MainThread) [custom_components.zha_toolkit] 'ieee' parameter: 'button.ubisys_c4_5504_identify' -> IEEE Addr: '00:1f:ee:00:00:00:9a:e3'
2023-10-17 13:11:26.706 DEBUG (MainThread) [custom_components.zha_toolkit] Default handler for attr_write
2023-10-17 13:11:26.706 DEBUG (MainThread) [custom_components.zha_toolkit] Handler: <function command_handler_default at 0xffff9853c900>
2023-10-17 13:11:26.707 DEBUG (MainThread) [custom_components.zha_toolkit] running default command: <ServiceCall zha_toolkit.attr_write (c:01HCYNAQEB8VBEP9BNR4F4CTCA): ieee=button.ubisys_c4_5504_identify, endpoint=232, cluster=64512, attribute=1, attr_type=72, attr_val=41040006000d0106000206010d0206000206020d0306000206030d04060002, read_before_write=True, read_after_write=False, use_cache=False>
2023-10-17 13:11:26.708 DEBUG (MainThread) [custom_components.zha_toolkit.default] Trying to import custom_components.zha_toolkit.zcl_attr to call attr_write
2023-10-17 13:11:26.715 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Request attr read [1]
2023-10-17 13:11:26.760 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Reading attr result (attrs, status): ({1: Array(type=AnonymousLVList, value=[b'\x00\r\x01\x06\x00\x02', b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02', b'\x03\r\x04\x06\x00\x02'])}, {})
2023-10-17 13:11:26.760 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Type determined from read: 0x48
2023-10-17 13:11:26.761 DEBUG (MainThread) [custom_components.zha_toolkit.utils] Data type '<class 'zigpy.zcl.foundation.Array'>' for attr type 72
2023-10-17 13:11:26.761 DEBUG (MainThread) [custom_components.zha_toolkit.utils] Converted 41040006000d0106000206010d0206000206020d0306000206030d04060002 to TypeValue(type=Array, value=Array(type=NoneType, value=None)) - will compare to Array(type=NoneType, value=None) - Type: 0x48
2023-10-17 13:11:26.761 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Request attr write [Attribute(attrid=0x0001, value=TypeValue(type=Array, value=Array(type=NoneType, value=None)))]
2023-10-17 13:11:26.762 DEBUG (MainThread) [custom_components.zha_toolkit] event_data {'zha_toolkit_version': 'v1.1.2', 'zigpy_version': '0.58.0.post2+git.80f9f8db', 'zigpy_rf_version': '0.35.9', 'ieee_org': 'button.ubisys_c4_5504_identify', 'ieee': '00:1f:ee:00:00:00:9a:e3', 'command': 'attr_write', 'command_data': None, 'start_time': '2023-10-17T11:11:26.705662+00:00', 'errors': ['AttributeError("\'str\' object has no attribute \'to_bytes\'")'], 'params': {'endpoint_id': 232, 'cluster_id': 64512, 'attr_id': 1, 'attr_type': 72, 'attr_val': '41040006000d0106000206010d0206000206020d0306000206030d04060002', 'dir': 0, 'tries': 1, 'expect_reply': True, 'args': [], 'read_before_write': True}, 'compare_val': Array(type=NoneType, value=None), 'attr_type': '0x48', 'write_is_equal': False, 'read_before': ({1: Array(type=AnonymousLVList, value=[b'\x00\r\x01\x06\x00\x02', b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02', b'\x03\r\x04\x06\x00\x02'])}, {}), 'success': False}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 816, in toolkit_service
    raise handler_exception
  File "/config/custom_components/zha_toolkit/__init__.py", line 780, in toolkit_service
    handler_result = await handler(
                     ^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 882, in command_handler_default
    return await default.default(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/default.py", line 40, in default
    await handler(app, listener, ieee, cmd, data, service, params, event_data)
  File "/config/custom_components/zha_toolkit/zcl_attr.py", line 462, in attr_write
    result_write = await u.cluster__write_attributes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/utils.py", line 964, in cluster__write_attributes
    return await cluster._write_attributes(attrs, manufacturer=manufacturer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/pyt [...]

2023-10-17 11:19 UTC, tomasbedrich commented on custom_components/zha_toolkit/utils.py
> +        array_type = attr_val_in[0]
I don't know how it is possible that your example of array write works. When I try it (irrespectively of expected effect on the end device), I get the same `AttributeError: 'list' object has no attribute 'to_bytes'` as below.

2023-10-17 11:24 UTC, tomasbedrich commented
I believe the most important thing is that ZCL Arrays [are typed collections](https://github.com/zigpy/zigpy/blob/80f9f8dbdf077add9f5588ec2d5e9be654f5169e/zigpy/zcl/foundation.py#L130). The [generic encoding logic](https://github.com/mdeweerd/zha-toolkit/blob/50c46d5f7d6430127f67e28133a5f46e6fd75261/custom_components/zha_toolkit/utils.py#L615C36-L615C36) only creates an Array object with a single parameter, while Array needs _two parameters_ to be constructed - item type, contents.

2023-10-17 15:35 UTC, tomasbedrich commented on README.md
> +        Elements Type: 56-Bit Bitmap (0x1e)
I don't understand where does this "Elements Type" (0x1e) come from. Can you please explain? This was the `array_type` in my original PR.

2023-10-17 16:21 UTC, mdeweerd commented on README.md
> +        Elements Type: 56-Bit Bitmap (0x1e)
I also wonder how this 0x1e gets there, when I change the array size, the type changes... .
I think that the generic implementation needs further investigation so that for arrays the raw data is used - I have not yet been succeeded to replicate sending Array data with the generic code.

2023-10-17 16:23 UTC, mdeweerd commented on README.md
> +  #  So here: `4, 0` is 0x0004, so two elements in the array, each of 56 bytes.
Initially I made the example smaller with only two items in the array, which led to learning that this did not work with the genreic code.
I update the readme.

2023-10-17 16:25 UTC, mdeweerd commented on README.md
> +  attr_val: [65, 4, 0, 6, 0, 13, 1, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2]
I now understand that this is the type of the array elements.

2023-10-18 08:58 UTC, tomasbedrich commented
Anything else I can help w.r.t. this PR?

2023-10-18 09:02 UTC, mdeweerd commented
> Anything else I can help w.r.t. this PR?

Yes, I invited you to verify the "compare_val" as I can not try it myself on a device.

2023-10-18 09:24 UTC, tomasbedrich commented
With version https://github.com/mdeweerd/zha-toolkit/pull/210/commits/561e95e3bbd813530c14f4c9c29678ef844b4cd0, I have this result:

```yaml
service: zha_toolkit.attr_write
data:
  ieee: button.ubisys_c4_5504_identify
  endpoint: 232
  cluster: 64512
  attribute: 1
  attr_type: 0x48
  attr_val: [65, 4, 0, 6, 0, 13, 1, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2]
  read_before_write: false
  read_after_write: true
  use_cache: false
```

res:

```
zha_toolkit_version: v1.1.2
zigpy_version: 0.58.0.post2+git.80f9f8db
zigpy_rf_version: 0.35.9
ieee_org: button.ubisys_c4_5504_identify
ieee: 00:1f:ee:00:00:00:9a:e3
command: attr_write
command_data: null
start_time: "2023-10-18T09:19:18.987042+00:00"
errors: []
params:
  endpoint_id: 232
  cluster_id: 64512
  attr_id: 1
  attr_type: 72
  attr_val:
    - 65
    - 4
    - 0
    - 6
    - 0
    - 13
    - 1
    - 6
    - 0
    - 2
    - 6
    - 1
    - 13
    - 2
    - 6
    - 0
    - 2
    - 6
    - 2
    - 13
    - 3
    - 6
    - 0
    - 2
    - 6
    - 3
    - 13
    - 4
    - 6
    - 0
    - 2
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  read_after_write: true
compare_val:
  - 65
  - 4
  - 0
  - 6
  - 0
  - 13
  - 1
  - 6
  - 0
  - 2
  - 6
  - 1
  - 13
  - 2
  - 6
  - 0
  - 2
  - 6
  - 2
  - 13
  - 3
  - 6
  - 0
  - 2
  - 6
  - 3
  - 13
  - 4
  - 6
  - 0
  - 2
attr_type: "0x48"
write_is_equal: false
result_write:
  - - status: 0
      attrid: null
result_read: >-
  ({1: Array(type=AnonymousLVList, value=[b'\x00\r\x01\x06\x00\x02',
  b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02',
  b'\x03\r\x04\x06\x00\x02'])}, {})
success: false
```

While the `compare_val` equals to what was written, the result read is different because `zigpy` parses the Array structure. Based of that, `zha_toolkit` returns `write_is_equal: false`, which is a bit misleading. This is why I originally returned `compare_val = None` for this raw array write.

2023-10-18 10:05 UTC, mdeweerd commented
Ok, zigpy returns the list but I'ld expecte the serialised value is compared, except that the structure is reported.

I've updated the code to report the serialized values when the match fails.  So based on that we can update the "compare_val" to what would actually match when the read succeeds.  (That code change is untested, so might need some adjustments).

https://github.com/mdeweerd/zha-toolkit/pull/210/commits/28e92d4c31b9b9235030c622ed5cb1c1b667de4b#diff-3cff7aaa1d7e2385a2d66097c78d84cf4bd88f08e74e77ddcddb1158b6f88376R498-R508

2023-10-19 08:55 UTC, tomasbedrich commented
I rebased the branch to incorporate another fixes from `main` and ran another series of tests. Now it looks like:

```yaml
service: zha_toolkit.attr_write
data:
  ieee: button.ubisys_c4_5504_identify
  endpoint: 232
  cluster: 64512
  attribute: 1
  attr_type: 0x48
  attr_val: [65, 4, 0, 6, 0, 13, 1, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2]
  read_before_write: false
  read_after_write: true
  use_cache: false
```

res:

```yaml
zha_toolkit_version: v1.1.2
zigpy_version: 0.58.0.post2+git.80f9f8db
zigpy_rf_version: 0.35.9
ieee_org: button.ubisys_c4_5504_identify
ieee: 00:1f:ee:00:00:00:9a:e3
command: attr_write
command_data: null
start_time: "2023-10-19T08:52:32.396584+00:00"
errors: []
params:
  endpoint_id: 232
  cluster_id: 64512
  attr_id: 1
  attr_type: 72
  attr_val:
    - 65
    - 4
    - 0
    - 6
    - 0
    - 13
    - 1
    - 6
    - 0
    - 2
    - 6
    - 1
    - 13
    - 2
    - 6
    - 0
    - 2
    - 6
    - 2
    - 13
    - 3
    - 6
    - 0
    - 2
    - 6
    - 3
    - 13
    - 4
    - 6
    - 0
    - 2
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  read_after_write: true
compare_val:
  - 65
  - 4
  - 0
  - 6
  - 0
  - 13
  - 1
  - 6
  - 0
  - 2
  - 6
  - 1
  - 13
  - 2
  - 6
  - 0
  - 2
  - 6
  - 2
  - 13
  - 3
  - 6
  - 0
  - 2
  - 6
  - 3
  - 13
  - 4
  - 6
  - 0
  - 2
attr_type: "0x48"
write_is_equal: false
result_write:
  - - status: 0
      attrid: null
warnings:
  - >-
    Read does not match expected:
    b'A\x04\x00\x06\x00\r\x01\x06\x00\x02\x06\x01\r\x02\x06\x00\x02\x06\x02\r\x03\x06\x00\x02\x06\x03\r\x04\x06\x00\x02'
    <>
    b'A\x04\x00\x06\x00\r\x01\x06\x00\x02\x06\x01\r\x02\x06\x00\x02\x06\x02\r\x03\x06\x00\x02\x06\x03\r\x04\x06\x00\x02'
result_read: >-
  ({1: Array(type=AnonymousLVList, value=[b'\x00\r\x01\x06\x00\x02',
  b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02',
  b'\x03\r\x04\x06\x00\x02'])}, {})
success: false
```

2023-10-19 12:54 UTC, mdeweerd commented
Thank you.
I see that the serialized data matches, so this is what needs to be compared - currently that is not the case.  You can update the code for that and test or I'll do it later (but I can not test).
The serialisation is done when generating the "Read does not match expected" message (added to see if that would match).

2023-10-24 17:05 UTC, mdeweerd approved these changes

2023-10-24 17:07 UTC, mdeweerd commented
I've updated the code to compare serialised values before and after the write.

I also enabled reading Arrays in scan_device - I think I disabled it because I had issues with, now fixed in zigpy.

Can you test this on your device.  scan_device might not result in an array read if your device does not support "scanning" that attribute.

2023-10-24 21:51 UTC, tomasbedrich commented
As for the scanning, I cannot see any attributes, not even for standard clusters, so I cannot evaluate if this improved the behaviour for Arrays or not:

```yaml
service: zha_toolkit.scan_device
data:
  ieee: button.ubisys_c4_5504_identify
  endpoint: [1, 232]
```

the output is following:

```yaml
zha_toolkit_version: v1.1.2
zigpy_version: 0.58.0.post2+git.80f9f8db
zigpy_rf_version: 0.35.9
ieee_org: button.ubisys_c4_5504_identify
ieee: 00:1f:ee:00:00:00:9a:e3
command: scan_device
command_data: null
start_time: "2023-10-24T21:49:17.305585+00:00"
errors: []
params:
  endpoint_id:
    - 1
    - 232
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  read_before_write: true
  read_after_write: true
scan:
  ieee: 00:1f:ee:00:00:00:9a:e3
  nwk: "0xcb79"
  model: C4 (5504)
  manufacturer: ubisys
  manufacturer_id: "0x4338"
  endpoints:
    - id: 1
      device_type: "0x0104"
      profile: "0x0104"
      in_clusters:
        "0x0000":
          cluster_id: "0x0000"
          title: Basic
          name: basic
          attributes: {}
          commands_received: {}
          commands_generated: {}
        "0x0003":
          cluster_id: "0x0003"
          title: Identify
          name: identify
          attributes: {}
          commands_received: {}
          commands_generated: {}
      out_clusters:
        "0x0005":
          cluster_id: "0x0005"
          title: Scenes
          name: scenes
          attributes: {}
          commands_received: {}
          commands_generated: {}
        "0x0006":
          cluster_id: "0x0006"
          title: On/Off
          name: on_off
          attributes: {}
          commands_received: {}
          commands_generated: {}
        "0x0008":
          cluster_id: "0x0008"
          title: Level control
          name: level
          attributes: {}
          commands_received: {}
          commands_generated: {}
        "0x0300":
          cluster_id: "0x0300"
          title: Color Control
          name: light_color
          attributes: {}
          commands_received: {}
          commands_generated: {}
    - id: 232
      device_type: "0x0507"
      profile: "0x0104"
      in_clusters:
        "0x0000":
          cluster_id: "0x0000"
          title: Basic
          name: basic
          attributes: {}
          commands_received: {}
          commands_generated: {}
        "0xfc00":
          cluster_id: "0xfc00"
          title: Manufacturer Specific
          name: manufacturer_specific
          attributes: {}
          commands_received: {}
          commands_generated: {}
      out_clusters:
        "0x0003":
          cluster_id: "0x0003"
          title: Identify
          name: identify
          attributes: {}
          commands_received: {}
          commands_generated: {}
        "0x0019":
          cluster_id: "0x0019"
          title: Ota
          name: ota
          attributes: {}
          commands_received: {}
          commands_generated: {}
success: true
```

2023-10-24 21:59 UTC, tomasbedrich commented
As for the write:

```yaml
service: zha_toolkit.attr_write
data:
  ieee: button.ubisys_c4_5504_identify
  endpoint: 232
  cluster: 64512
  attribute: 1
  attr_type: 0x48
  attr_val: [65, 4, 0, 6, 0, 13, 1, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2]
```

This works okay as long as `attr_val` is the same as the actual value read:

```yaml
zha_toolkit_version: v1.1.2
zigpy_version: 0.58.0.post2+git.80f9f8db
zigpy_rf_version: 0.35.9
ieee_org: button.ubisys_c4_5504_identify
ieee: 00:1f:ee:00:00:00:9a:e3
command: attr_write
command_data: null
start_time: "2023-10-24T21:56:22.879429+00:00"
errors: []
params:
  endpoint_id: 232
  cluster_id: 64512
  attr_id: 1
  attr_type: 72
  attr_val:
    - 65
    - 4
    - 0
    - 6
    - 0
    - 13
    - 1
    - 6
    - 0
    - 2
    - 6
    - 1
    - 13
    - 2
    - 6
    - 0
    - 2
    - 6
    - 2
    - 13
    - 3
    - 6
    - 0
    - 2
    - 6
    - 3
    - 13
    - 4
    - 6
    - 0
    - 2
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  read_before_write: true
  read_after_write: true
compare_val:
  - 65
  - 4
  - 0
  - 6
  - 0
  - 13
  - 1
  - 6
  - 0
  - 2
  - 6
  - 1
  - 13
  - 2
  - 6
  - 0
  - 2
  - 6
  - 2
  - 13
  - 3
  - 6
  - 0
  - 2
  - 6
  - 3
  - 13
  - 4
  - 6
  - 0
  - 2
attr_type: "0x48"
write_is_equal: true
info: Data read is equal to data to write
result_read: >-
  ({1: Array(type=AnonymousLVList, value=[b'\x00\r\x01\x06\x00\x02',
  b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02',
  b'\x03\r\x04\x06\x00\x02'])}, {})
success: true
```

**But**, when I change the contents of `attr_val` (only a single byte), I get the following error back in HA logs:

```python
2023-10-24 23:54:52.823 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Reading attr result (attrs, status): ({1: Array(type=AnonymousLVList, value=[b'\x00\r\x02\x06\x00\x02', b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02', b'\x03\r\x04\x06\x00\x02'])}, {})
2023-10-24 23:54:52.831 DEBUG (MainThread) [custom_components.zha_toolkit] event_data {'zha_toolkit_version': 'v1.1.2', 'zigpy_version': '0.58.0.post2+git.80f9f8db', 'zigpy_rf_version': '0.35.9', 'ieee_org': 'button.ubisys_c4_5504_identify', 'ieee': '00:1f:ee:00:00:00:9a:e3', 'command': 'attr_write', 'command_data': None, 'start_time': '2023-10-24T21:54:52.659660+00:00', 'errors': [], 'params': {'endpoint_id': 232, 'cluster_id': 64512, 'attr_id': 1, 'attr_type': 72, 'attr_val': [65, 4, 0, 6, 0, 13, 2, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2], 'dir': 0, 'tries': 1, 'expect_reply': True, 'args': [], 'read_before_write': True, 'read_after_write': True}, 'compare_val': [65, 4, 0, 6, 0, 13, 2, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2], 'attr_type': '0x48', 'write_is_equal': False, 'read_before': ({1: Array(type=AnonymousLVList, value=[b'\x00\r\x01\x06\x00\x02', b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02', b'\x03\r\x04\x06\x00\x02'])}, {}), 'result_write': Write_Attributes_rsp(status_records=[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]), 'result_read': "({1: Array(type=AnonymousLVList, value=[b'\\x00\\r\\x02\\x06\\x00\\x02', b'\\x01\\r\\x02\\x06\\x00\\x02', b'\\x02\\r\\x03\\x06\\x00\\x02', b'\\x03\\r\\x04\\x06\\x00\\x02'])}, {})", 'success': True}
2023-10-24 23:54:52.834 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.result.response.read_before=({1: Array(type=AnonymousLVList, value=[b'\x00\r\x01\x06\x00\x02', b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02', b'\x03\r\x04\x06\x00\x02'])}, {})(<class 'tuple'>
```

2023-10-24 23:06 UTC, mdeweerd commented
There was some code to ensure that "result_read" could be converted to json, but not "read_before".  I fixed that as well as some regressions for scalar values.

2023-10-25 07:06 UTC, tomasbedrich commented
Not there yet:

```
2023-10-25 09:03:37.801 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Type determined from read: 0x48
2023-10-25 09:03:37.802 ERROR (MainThread) [custom_components.zha_toolkit.utils] Can't convert to JSON Array(type=AnonymousLVList, value=[b'\x00\r\x01\x06\x00\x02', b'\x01\r\x02\x06\x00\x02', b'\x02\r\x03\x06\x00\x02', b'\x03\r\x04\x06\x00\x02'])
2023-10-25 09:03:37.803 DEBUG (MainThread) [custom_components.zha_toolkit] event_data {'zha_toolkit_version': 'v1.1.2', 'zigpy_version': '0.58.0.post2+git.80f9f8db', 'zigpy_rf_version': '0.35.9', 'ieee_org': 'button.ubisys_c4_5504_identify', 'ieee': '00:1f:ee:00:00:00:9a:e3', 'command': 'attr_write', 'command_data': None, 'start_time': '2023-10-25T07:03:37.717141+00:00', 'errors': [], 'params': {'endpoint_id': 232, 'cluster_id': 64512, 'attr_id': 1, 'attr_type': 72, 'attr_val': [65, 4, 0, 6, 0, 13, 1, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2], 'dir': 0, 'tries': 1, 'expect_reply': True, 'args': [], 'read_before_write': True, 'read_after_write': True}, 'compare_val': [65, 4, 0, 6, 0, 13, 1, 6, 0, 2, 6, 1, 13, 2, 6, 0, 2, 6, 2, 13, 3, 6, 0, 2, 6, 3, 13, 4, 6, 0, 2], 'attr_type': '0x48', 'write_is_equal': True, 'info': 'Data read is equal to data to write', 'result_read': ({1: b'A\x04\x00\x06\x00\r\x01\x06\x00\x02\x06\x01\r\x02\x06\x00\x02\x06\x02\r\x03\x06\x00\x02\x06\x03\r\x04\x06\x00\x02'}, {}), 'success': True}
2023-10-25 09:03:37.805 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.result.response.result_read=({1: b'A\x04\x00\x06\x00\r\x01\x06\x00\x02\x06\x01\r\x02\x06\x00\x02\x06\x02\r\x03\x06\x00\x02\x06\x03\r\x04\x06\x00\x02'}, {})(<class 'tuple'>
```

2023-10-26 23:22 UTC, tomasbedrich commented
The current state now works on my side:

```yaml
zha_toolkit_version: v1.1.2
zigpy_version: 0.58.0.post2+git.80f9f8db
zigpy_rf_version: 0.35.9
ieee_org: button.ubisys_c4_5504_identify
ieee: 00:1f:ee:00:00:00:9a:e3
command: attr_write
command_data: null
start_time: "2023-10-26T23:19:39.655990+00:00"
errors: []
params:
  endpoint_id: 232
  cluster_id: 64512
  attr_id: 1
  attr_type: 72
  attr_val:
    - 65
    - 4
    - 0
    - 6
    - 0
    - 13
    - 1
    - 6
    - 0
    - 2
    - 6
    - 1
    - 13
    - 2
    - 6
    - 0
    - 2
    - 6
    - 2
    - 13
    - 3
    - 6
    - 0
    - 2
    - 6
    - 3
    - 13
    - 4
    - 6
    - 0
    - 2
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  read_before_write: true
  read_after_write: true
compare_val:
  - 65
  - 4
  - 0
  - 6
  - 0
  - 13
  - 1
  - 6
  - 0
  - 2
  - 6
  - 1
  - 13
  - 2
  - 6
  - 0
  - 2
  - 6
  - 2
  - 13
  - 3
  - 6
  - 0
  - 2
  - 6
  - 3
  - 13
  - 4
  - 6
  - 0
  - 2
attr_type: "0x48"
write_is_equal: false
read_before:
  - "1": 41040006000d0206000206010d0206000206020d0306000206030d04060002
  - {}
result_write:
  - - status: 0
      attrid: null
result_read:
  - "1": 41040006000d0106000206010d0206000206020d0306000206030d04060002
  - {}
success: true
```

2023-10-26 23:27 UTC, mdeweerd commented
Good news!
I can see why the order has to change, but I'ld like to keep the reported values as strings rather than conversions to hexadecimal values.  The string value can be reused as the input for another write.

2023-10-26 23:29 UTC, tomasbedrich commented
> The string value can be reused as the input for another write.

That's exactly why I added 5ba046e just now :)

2023-10-26 23:32 UTC, tomasbedrich commented
Up to you, if you think it needs more changes, please go ahead.

2023-10-27 00:06 UTC, mdeweerd commented
Well, providing the data as "hex" was not really the logic up to now, so I'm changing that back to the binary string type (or whatever that is called).

2023-10-27 00:34 UTC, merged

2023-10-27 00:49 UTC, mdeweerd commented
Merged & pre-released.

2023-10-27 09:15 UTC, tomasbedrich commented
I can confirm the pre-release works. Thanks.