Test that app has ota and ota has listeners for OTA operations
mdeweerd/zha-toolkit pull request #226
Opened 2024-05-04 00:07 UTC by systemcrash

Apparently in some situations they're absent. Let's guard against them.

Closes issue #225

2024-05-26 10:59 UTC, frli4797 requested changes
This commit seems to have to have two syntax errors with double colons on conditional statements. (Typo?) I've tried you PR with just removing these, which worked fine.

2024-05-26 10:59 UTC, frli4797 commented on custom_components/zha_toolkit/ota.py
> +    if hasattr(app, 'ota') and hasattr(app.ota, '_listeners')::
Syntax error '::'

2024-05-26 10:59 UTC, frli4797 commented on custom_components/zha_toolkit/ota.py
> +    if hasattr(app, 'ota') and hasattr(app.ota, '_listeners')::
Syntax error on '::'

2024-05-26 20:14 UTC, systemcrash commented on custom_components/zha_toolkit/ota.py
> +    if hasattr(app, 'ota') and hasattr(app.ota, '_listeners')::
yeah, typo

2024-07-30 17:43 UTC, merged

2024-07-30 17:44 UTC, mdeweerd commented
I've been quite busy for a while, I have just integrated this and making a release with the updates.
Thank you.